using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace HRTool.CommanMethods.RolesManagement
{
    public enum Menukey : int
    {
        Dashboard = 1,
        News = 2,
        Resources = 3,
        Me = 4,
        Document = 5,
        Planner = 6,
        ProjectPlanner = 7,
        Performance = 8,
        SkillsEndorsement = 9,
        Training = 10,
        Certification = 11,
        Visa = 12,
        Tasks = 13,
        Cases = 14,
        Approve = 16,
        TMS = 17,
        Notifications = 18,
        Queries = 19,
        BulkActions = 20,
        Reports = 21,
        OrganizationChart = 22,
        Settings = 23,
        Settings_TMS = 73,
        Settings_Projects = 74,
        Settings_Performance = 75,
        Settings_TechnicalSkillsSet = 76,
        Settings_GeneralSkillsSet = 77,
        Settings_AddSkills = 78,
        Settings_ActivityType = 79,
        Settings_AddCmpCustomer = 80,
        Settings_AddAssets = 81,
        Settings_Timesheet = 82,
        Settings_HolidaysAbsence = 83,
        Settings_Currency = 84,
        Settings_Administrators = 85,
        Settings_EmailSettings = 86,
        Settings_API = 87,
        Settings_Company = 88,
        Settings_CompanyStructure = 89,
        Settings_License = 91,
        Settings_Mobile = 92,
        Settings_OtherSettings = 95,
        Settings_SystemSettings = 92,
        Resources_OverView = 25,
        Resources_Planner = 26,
        Resources_ProjectPlanner = 27,
        Resources_Performance = 28,
        Resources_SkillsEndorsement = 29,
        Resources_Skills = 30,
        Resources_Training = 31,
        Resources_Documents = 32,
        Resources_Resume_CV = 33,
        Resources_Profile = 34,
        Resources_Employment = 35,
        Resources_Contacts = 36,
        Resources_Benefits = 37,
        Resources_Caselog = 38,
        Me_OverView = 39,
        Me_Planner = 40,
        Me_ProjectPlanner = 41,
        Me_Performance = 42,
        Me_SkillsEndorsement = 43,
        Me_Skills = 44,
        Me_Training = 45,
        Me_Documents = 46,
        Me_Resume_CV = 47,
        Me_Profile = 48,
        Me_Employment = 49,
        Me_Contacts = 50,
        Me_Benefits = 51,
        Me_Caselog = 52,
        Settings_CreateRole = 93,
        Settings_AssignRole = 94,
        Settings_RoleManagement = 95,
        NewsPost = 98

    }
}