//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRTool.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivityType
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> CurrencyID { get; set; }
        public Nullable<int> WorkUnitID { get; set; }
        public Nullable<int> Year { get; set; }
        public bool Archived { get; set; }
        public Nullable<int> UserIDCreatedBy { get; set; }
        public Nullable<int> UserIDLastModifiedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> LastModified { get; set; }
        public Nullable<decimal> WorkerRate { get; set; }
        public Nullable<decimal> CustomerRate { get; set; }
    }
}
