//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRTool.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin_Document
    {
        public int Id { get; set; }
        public string DocumentPath { get; set; }
        public string DocumentOriginalPath { get; set; }
        public string Description { get; set; }
        public string LinkDisplayText { get; set; }
        public string LinkURL { get; set; }
        public Nullable<int> BusinessID { get; set; }
        public Nullable<int> DivisionID { get; set; }
        public Nullable<int> PoolID { get; set; }
        public Nullable<int> FunctionID { get; set; }
        public Nullable<int> Category { get; set; }
        public bool EmployeeAccess { get; set; }
        public bool ManagerAccess { get; set; }
        public bool CustomerAccess { get; set; }
        public bool SpecificWorker { get; set; }
        public Nullable<int> WorkerID { get; set; }
        public bool SpecificManager { get; set; }
        public Nullable<int> ManagerID { get; set; }
        public bool SpecificCustomer { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public bool SignatureRequire { get; set; }
        public string IpAddress { get; set; }
        public bool Archived { get; set; }
        public Nullable<int> UserIDCreatedBy { get; set; }
        public Nullable<int> UserIDLastModifiedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> LastModified { get; set; }
    }
}
