//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRTool.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class BradfordFactor_HolidaySettings
    {
        public int Id { get; set; }
        public Nullable<int> LowerValue1 { get; set; }
        public Nullable<int> UpperValue1 { get; set; }
        public string Alert1 { get; set; }
        public Nullable<int> LowerValue2 { get; set; }
        public Nullable<int> UpperValue2 { get; set; }
        public string Alert2 { get; set; }
        public Nullable<int> LowerValue3 { get; set; }
        public Nullable<int> UpperValue3 { get; set; }
        public string Alert3 { get; set; }
        public Nullable<int> LowerValue4 { get; set; }
        public Nullable<int> UpperValue4 { get; set; }
        public string Alert4 { get; set; }
    }
}
