//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRTool.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class certificate
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> Type { get; set; }
        public string Body { get; set; }
        public string Number { get; set; }
        public Nullable<int> AssignTo { get; set; }
        public Nullable<int> InRelationTo { get; set; }
        public Nullable<System.DateTime> ValidFrom { get; set; }
        public Nullable<System.DateTime> ExpiringDate { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> AlertBeforeDays { get; set; }
        public Nullable<bool> Mandatory { get; set; }
        public Nullable<bool> Validate { get; set; }
        public string Description { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModified { get; set; }
        public Nullable<bool> Archived { get; set; }
    }
}
