//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRTool.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company_Settings
    {
        public int Id { get; set; }
        public string Logo { get; set; }
        public string Statement { get; set; }
        public Nullable<int> IndustryID { get; set; }
        public Nullable<int> DateFormat { get; set; }
        public Nullable<int> TimeFormat { get; set; }
        public Nullable<int> BaseCurrency { get; set; }
        public bool DailyAdminEmail { get; set; }
        public bool WeeklyManagerEmail { get; set; }
        public bool WeeklyEmployeeEmail { get; set; }
        public bool ManagerSeeEmployeeSalary { get; set; }
        public bool EmployeeSeeSalary { get; set; }
        public bool OrganisationChart { get; set; }
        public string OrganisationChartExternalLink { get; set; }
        public bool AllowEmployeeUploadPhoto { get; set; }
        public bool ManagerSeeEmployeeContactDetail { get; set; }
        public bool ManagerUploadDocument { get; set; }
        public bool CompanyReport { get; set; }
        public string ProbationPeriod { get; set; }
        public int EmployeeAccess { get; set; }
        public int ManagerAccess { get; set; }
        public bool OtherLeaveReasons { get; set; }
        public Nullable<int> UserIDCreatedBy { get; set; }
        public Nullable<int> UserIDLastModifiedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> LastModified { get; set; }
    }
}
