//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRTool.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Currency
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> FreezingDate { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public Nullable<decimal> FixedRate { get; set; }
        public Nullable<decimal> LiveRate { get; set; }
        public bool IsFixed { get; set; }
        public bool Archived { get; set; }
        public Nullable<int> UserIDCreatedBy { get; set; }
        public Nullable<int> UserIDLastModifiedBy { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> LastModified { get; set; }
    }
}
