//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRTool.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Email_Setting
    {
        public int Id { get; set; }
        public string From_Name { get; set; }
        public string From_Email { get; set; }
        public string User_Name { get; set; }
        public string Email_Password { get; set; }
        public string Server { get; set; }
        public Nullable<int> Port { get; set; }
        public Nullable<bool> Enable_SSL { get; set; }
    }
}
