//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRTool.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee_Task_Temp
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public Nullable<int> Category { get; set; }
        public Nullable<int> AssignTo { get; set; }
        public Nullable<int> InRelationTo { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<int> AlterBeforeDays { get; set; }
        public Nullable<int> Status { get; set; }
        public string Description { get; set; }
        public Nullable<bool> Archived { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> LastModified { get; set; }
    }
}
