//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRTool.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee_TravelLeave
    {
        public int Id { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public Nullable<int> FromCountryId { get; set; }
        public Nullable<int> FromStateId { get; set; }
        public Nullable<int> FromTownId { get; set; }
        public Nullable<int> FromAirportId { get; set; }
        public Nullable<int> ToCountryId { get; set; }
        public Nullable<int> ToStateId { get; set; }
        public Nullable<int> ToTownId { get; set; }
        public Nullable<int> ToAirportId { get; set; }
        public Nullable<int> ReasonForTravelId { get; set; }
        public Nullable<bool> IsLessThenADay { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<decimal> Duration { get; set; }
        public Nullable<int> StartTimeHour { get; set; }
        public Nullable<int> StartTimeMin { get; set; }
        public Nullable<int> EndTimeHour { get; set; }
        public Nullable<int> EndTimeMin { get; set; }
        public Nullable<decimal> DurationHr { get; set; }
        public string Comment { get; set; }
        public Nullable<int> Type { get; set; }
        public string Customer { get; set; }
        public Nullable<int> Project { get; set; }
        public Nullable<int> CostCode { get; set; }
        public Nullable<bool> Archived { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
        public string ApprovalStatus { get; set; }
        public Nullable<System.DateTime> ApprovalDate { get; set; }
        public string Status { get; set; }
        public bool IsRead { get; set; }
        public Nullable<bool> IsReadHR { get; set; }
        public Nullable<bool> IsReadAddReport { get; set; }
    }
}
