//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRTool.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeAddressInfo
    {
        public int ContactInfoId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> CountryId { get; set; }
        public Nullable<int> StateId { get; set; }
        public Nullable<int> TownId { get; set; }
        public Nullable<int> AirportId { get; set; }
        public string HousNumber { get; set; }
        public string PostCode { get; set; }
        public string ContactAddress { get; set; }
        public string PersonalPhone { get; set; }
        public string PersonalMobile { get; set; }
        public string PersonalEmail { get; set; }
    }
}
