//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRTool.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee_Languages
    {
        public int Id { get; set; }
        public Nullable<int> LanguageID { get; set; }
        public Nullable<int> SpeakingID { get; set; }
        public Nullable<int> ListeningID { get; set; }
        public Nullable<int> WritingID { get; set; }
        public Nullable<int> ReadingID { get; set; }
        public int EmployeeID { get; set; }
        public bool Archived { get; set; }
        public Nullable<int> UserIDCreatedBy { get; set; }
        public Nullable<int> UserIDLastModifiedBy { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> LastModified { get; set; }
    }
}
