//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRTool.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee_Salary_Deduction
    {
        public int Id { get; set; }
        public int EmployeeSalaryID { get; set; }
        public Nullable<int> Deduction { get; set; }
        public decimal FixedAmount { get; set; }
        public decimal PercentOfSalary { get; set; }
        public bool IncludeInSalary { get; set; }
        public string Comments { get; set; }
        public bool Archived { get; set; }
        public Nullable<int> UserIDCreatedBy { get; set; }
        public Nullable<int> UserIDLastModifiedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> LastModified { get; set; }
    }
}
