//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRTool.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee_SickLeaves
    {
        public int Id { get; set; }
        public int EmployeeId { get; set; }
        public bool IsADayOrMore { get; set; }
        public bool IsHalfDay { get; set; }
        public bool IsHours { get; set; }
        public Nullable<int> Reason { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<decimal> DurationDays { get; set; }
        public string PartOfDay { get; set; }
        public Nullable<decimal> DurationHours { get; set; }
        public bool EmergencyLeave { get; set; }
        public bool ConfirmedbyHR { get; set; }
        public bool SelfCertificationFormRequired { get; set; }
        public Nullable<System.DateTime> SelfCertificateReceivedDate { get; set; }
        public bool BackToWorkInterviewRequired { get; set; }
        public Nullable<System.DateTime> InterviewDate { get; set; }
        public string InterviewConductedBy { get; set; }
        public bool IsPaid { get; set; }
        public bool IsPaidatotherrate { get; set; }
        public bool IsUnpaid { get; set; }
        public bool DoctorConsulted { get; set; }
        public string DoctorName { get; set; }
        public Nullable<System.DateTime> DateOfVisit { get; set; }
        public string TimeOfVisit { get; set; }
        public Nullable<System.DateTime> MedicalCertificateIssuedDate { get; set; }
        public string DoctorAdvice { get; set; }
        public string MedicationPrescribed { get; set; }
        public string WhyDoctorNotConsulted { get; set; }
        public bool IsDuaToAccident { get; set; }
        public bool Archived { get; set; }
        public Nullable<int> UserIDCreatedBy { get; set; }
        public Nullable<int> UserIDLastModifiedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> LastModified { get; set; }
        public string IssueAtWork { get; set; }
        public string Type { get; set; }
        public Nullable<System.DateTime> ApprovalDate { get; set; }
        public Nullable<bool> IsRead { get; set; }
        public string ApprovalStatus { get; set; }
        public Nullable<bool> IsReadHR { get; set; }
        public Nullable<bool> IsReadAddRep { get; set; }
    }
}
