//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRTool.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee_MaternityOrPaternityLeaves
    {
        public int Id { get; set; }
        public int EmployeeID { get; set; }
        public System.DateTime DueDate { get; set; }
        public Nullable<System.DateTime> ExptectedBirthWeekStartDate { get; set; }
        public Nullable<System.DateTime> ExptectedBirthWeekEndDate { get; set; }
        public Nullable<System.DateTime> OrdinaryMaternityLeaveStartDate { get; set; }
        public Nullable<System.DateTime> OrdinaryMaternityLeaveEndDate { get; set; }
        public Nullable<System.DateTime> AdditionalMaternityLeaveStartDate { get; set; }
        public Nullable<System.DateTime> AdditionalMaternityLeaveEndDate { get; set; }
        public Nullable<System.DateTime> EarliestBirthWeekStartDate { get; set; }
        public Nullable<System.DateTime> ActualStartDate { get; set; }
        public Nullable<System.DateTime> ActualEndDate { get; set; }
        public bool Archived { get; set; }
        public Nullable<int> UserIDCreatedBy { get; set; }
        public Nullable<int> UserIDLastModifiedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> LastModified { get; set; }
        public string Link { get; set; }
        public Nullable<System.DateTime> ApprovalDate { get; set; }
        public string ApprovalStatus { get; set; }
        public Nullable<bool> IsRead { get; set; }
        public Nullable<bool> IsReadHR { get; set; }
        public Nullable<bool> IsReadAddRes { get; set; }
    }
}
