//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRTool.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeBankInfo
    {
        public int BankInfoId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string BankName { get; set; }
        public string BankCode { get; set; }
        public string AccountNumber { get; set; }
        public string OtherAccountInformation { get; set; }
        public string AccountName { get; set; }
        public string BankAddress { get; set; }
        public string IBAN_No { get; set; }
        public string SWIFT_Code { get; set; }
    }
}
