//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRTool.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeePerformance
    {
        public int Id { get; set; }
        public int EmployeeId { get; set; }
        public int ProjectId { get; set; }
        public int ReviewId { get; set; }
        public Nullable<int> RevviewByEmpID { get; set; }
        public string PerformanceStatus { get; set; }
        public string OverallScore { get; set; }
        public string JobRoleScore { get; set; }
        public string OverallComments { get; set; }
        public Nullable<System.DateTime> ReviewDate { get; set; }
        public string ReviewStatus { get; set; }
        public Nullable<bool> Archived { get; set; }
        public Nullable<int> UserIDCreatedBy { get; set; }
        public Nullable<int> UserIDLastModifiedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
    }
}
