//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRTool.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeePerformanceGoal
    {
        public int Id { get; set; }
        public Nullable<int> EmployeePerformanceId { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public string GoalName { get; set; }
        public string GoalDescription { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public string GoalStatus { get; set; }
        public Nullable<decimal> GoalValueX { get; set; }
        public Nullable<decimal> GoalValueY { get; set; }
        public Nullable<bool> Archived { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public string Unit { get; set; }
    }
}
