//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRTool.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee_ProjectPlanner_Uplift
    {
        public int Id { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<int> UpliftPostionId { get; set; }
        public Nullable<decimal> WorkerRate { get; set; }
        public Nullable<decimal> WorkerRatePer { get; set; }
        public Nullable<decimal> CustomerRate { get; set; }
        public Nullable<decimal> CustomerRatePer { get; set; }
        public string CustomerId { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public string Comments { get; set; }
        public Nullable<bool> Archived { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
    }
}
