//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRTool.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class HolidayYearAndMonthSetting
    {
        public int Id { get; set; }
        public int HolidaysNAbsenceID { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<int> StartYear { get; set; }
        public Nullable<int> EndYear { get; set; }
        public Nullable<int> StartMonth { get; set; }
        public Nullable<int> EndMonth { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> PublicHoliday { get; set; }
    }
}
