//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRTool.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class HolidaysNAbsence_Setting
    {
        public int Id { get; set; }
        public string WorkingHours { get; set; }
        public string WorkPattern { get; set; }
        public string AnnualLeave { get; set; }
        public string CarryOverDays { get; set; }
        public string CarryOverHours { get; set; }
        public string HolidayYear { get; set; }
        public string PublicHolidayTemplate { get; set; }
        public bool TotalHolidayEntitlement { get; set; }
        public string HolidayEntitlement { get; set; }
        public bool HolidayReturn { get; set; }
        public bool AuthoriseHolidays { get; set; }
        public string TOILPeriod { get; set; }
        public bool BradfordFactorAlerts { get; set; }
        public string CalculationPeriod { get; set; }
    }
}
