//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRTool.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu_List
    {
        public int ID { get; set; }
        public string MenuName { get; set; }
        public string ActionName { get; set; }
        public string ControllerName { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
        public Nullable<int> SubmenuID { get; set; }
        public Nullable<System.DateTime> Createdate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<bool> IsDefaultAllocation { get; set; }
        public Nullable<int> MenuKey { get; set; }
    }
}
