//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRTool.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        public int Id { get; set; }
        public string Subject { get; set; }
        public string Description { get; set; }
        public Nullable<bool> EmployeeAccess { get; set; }
        public Nullable<bool> ManagerAccess { get; set; }
        public Nullable<bool> CustomerAccess { get; set; }
        public Nullable<bool> NotifyEmployeeViaEmail { get; set; }
        public Nullable<bool> AllowCustomer { get; set; }
        public Nullable<bool> SpecificWorker { get; set; }
        public Nullable<int> WorkerID { get; set; }
        public Nullable<bool> SpecificManager { get; set; }
        public Nullable<int> ManagerID { get; set; }
        public Nullable<bool> SpecificCustomer { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<bool> Archived { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
    }
}
