//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRTool.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PerformanceSetting
    {
        public int Id { get; set; }
        public string ReviewText { get; set; }
        public Nullable<System.DateTime> CompletionDate { get; set; }
        public Nullable<bool> AnnualReview { get; set; }
        public string CompanyCSV { get; set; }
        public string LocationCSV { get; set; }
        public string DivisionCSV { get; set; }
        public string JobRoleCSV { get; set; }
        public string EmploymentTypeCSV { get; set; }
        public string BusinessCSV { get; set; }
        public string PoolCSV { get; set; }
        public string FunctionCSV { get; set; }
        public string OverallScoreJson { get; set; }
        public string CoreSegmentJSON { get; set; }
        public string JobRoleSegmentJSON { get; set; }
        public string CoWorkerSegmentJSON { get; set; }
        public string CustomerSegmentJSON { get; set; }
        public bool Archived { get; set; }
        public Nullable<int> UserIDCreatedBy { get; set; }
        public Nullable<int> UserIDLastModifiedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> LastModified { get; set; }
        public Nullable<bool> RatingOverAll { get; set; }
        public Nullable<bool> RatingCore { get; set; }
        public Nullable<bool> RatingJobRole { get; set; }
        public string CSUserLastModifiedBy_Id { get; set; }
        public string GuID { get; set; }
    }
}
