//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRTool.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PerformanceCustomerDetail
    {
        public int Id { get; set; }
        public Nullable<int> Performance_Id { get; set; }
        public Nullable<int> InviteCustomer_Id { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public string CustomerScore { get; set; }
        public string Comments { get; set; }
        public string CusomerSegmentsJSON { get; set; }
        public string InviteStatus { get; set; }
        public Nullable<bool> IsArchived { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
    }
}
