//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRTool.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PerformanceEmployeeDetail
    {
        public int Id { get; set; }
        public Nullable<int> Performance_Id { get; set; }
        public string CoreScore { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public Nullable<int> IsManager_Id { get; set; }
        public Nullable<int> Performance_ManagerId { get; set; }
        public string OverAllScoreJSON { get; set; }
        public string Comments { get; set; }
        public Nullable<bool> IsArchived { get; set; }
        public Nullable<int> UserIDCreatedBy { get; set; }
        public Nullable<int> UserIDLastModifiedBy { get; set; }
        public Nullable<System.DateTime> UserIDCreatedDate { get; set; }
        public Nullable<System.DateTime> UserIDLastModifiedDate { get; set; }
        public Nullable<int> ReviewID { get; set; }
        public Nullable<bool> IsFormCompleted { get; set; }
    }
}
