//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRTool.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PerformanceCoWorkerDetail
    {
        public int Id { get; set; }
        public Nullable<int> PerformanceId { get; set; }
        public string Status { get; set; }
        public string CoreScore { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<int> InviteEmployeeId { get; set; }
        public Nullable<bool> InviteStatus { get; set; }
        public string CoWorkerScoreJSC { get; set; }
        public Nullable<bool> Archived { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
    }
}
