//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRTool.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class QueryColunName
    {
        public int Id { get; set; }
        public Nullable<int> TableId { get; set; }
        public string DisplayName { get; set; }
        public string ColumnName { get; set; }
    }
}
