//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRTool.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SendReviewToCoworker
    {
        public int Id { get; set; }
        public Nullable<int> ReviewID { get; set; }
        public Nullable<int> PerformanceID { get; set; }
        public Nullable<int> InviteeEmployee { get; set; }
        public Nullable<int> EmployeeOfReview { get; set; }
        public string CoreScore { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public string MailStatus { get; set; }
        public Nullable<bool> Archived { get; set; }
        public Nullable<System.DateTime> EmailSentDate { get; set; }
        public Nullable<int> EmailSentBy { get; set; }
        public string CoWorkerScoreJSC { get; set; }
        public string FullName { get; set; }
    }
}
