//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRTool.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TMS_Applicant
    {
        public int Id { get; set; }
        public int VacancyID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public int GenderID { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string PostalCode { get; set; }
        public string Address { get; set; }
        public string OtherContactDetails { get; set; }
        public int StatusID { get; set; }
        public string CoverLetterPathOriginal { get; set; }
        public string CoverLetterPath { get; set; }
        public string DownloadApplicationFormLink { get; set; }
        public string UploadApplicationFormPathOriginal { get; set; }
        public string UploadApplicationFormPath { get; set; }
        public string ResumePathOriginal { get; set; }
        public string ResumePath { get; set; }
        public string Question1Answer { get; set; }
        public string Question2Answer { get; set; }
        public string Question3Answer { get; set; }
        public string Question4Answer { get; set; }
        public string Question5Answer { get; set; }
        public Nullable<int> SourceID { get; set; }
        public string CompatencyJSV { get; set; }
        public string CommentJSV { get; set; }
        public string DocumentJSV { get; set; }
        public string GeneralSkillsJSV { get; set; }
        public string TechnicalSkillsJSV { get; set; }
        public string Cost { get; set; }
        public bool Archived { get; set; }
        public Nullable<int> UserIDCreatedBy { get; set; }
        public Nullable<int> UserIDLastModifiedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> LastModified { get; set; }
        public Nullable<int> RejectReasonId { get; set; }
        public string RejectReasonComment { get; set; }
        public Nullable<bool> IsReadHiringLead { get; set; }
    }
}
