//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRTool.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkPatternDetail
    {
        public int Id { get; set; }
        public int WorkPatternID { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> MondayHours { get; set; }
        public Nullable<decimal> MondayDays { get; set; }
        public Nullable<System.DateTime> MondayStart { get; set; }
        public Nullable<System.DateTime> MondayEnd { get; set; }
        public Nullable<int> MondayBreakMins { get; set; }
        public Nullable<decimal> TuesdayHours { get; set; }
        public Nullable<decimal> TuesdayDays { get; set; }
        public Nullable<System.DateTime> TuesdayStart { get; set; }
        public Nullable<System.DateTime> TuesdayEnd { get; set; }
        public Nullable<int> TuesdayBreakMins { get; set; }
        public Nullable<decimal> WednessdayHours { get; set; }
        public Nullable<decimal> WednessdayDays { get; set; }
        public Nullable<System.DateTime> WednessdayStart { get; set; }
        public Nullable<System.DateTime> WednessdayEnd { get; set; }
        public Nullable<int> WednessdayBreakMins { get; set; }
        public Nullable<decimal> ThursdayHours { get; set; }
        public Nullable<decimal> ThursdayDays { get; set; }
        public Nullable<System.DateTime> ThursdayStart { get; set; }
        public Nullable<System.DateTime> ThursdayEnd { get; set; }
        public Nullable<int> ThursdayBreakMins { get; set; }
        public Nullable<decimal> FridayHours { get; set; }
        public Nullable<decimal> FridayDays { get; set; }
        public Nullable<System.DateTime> FridayStart { get; set; }
        public Nullable<System.DateTime> FridayEnd { get; set; }
        public Nullable<int> FridayBreakMins { get; set; }
        public Nullable<decimal> SaturdayHours { get; set; }
        public Nullable<decimal> SaturdayDays { get; set; }
        public Nullable<System.DateTime> SaturdayStart { get; set; }
        public Nullable<System.DateTime> SaturdayEnd { get; set; }
        public Nullable<int> SaturdayBreakMins { get; set; }
        public Nullable<decimal> SundayHours { get; set; }
        public Nullable<decimal> SundayDays { get; set; }
        public Nullable<System.DateTime> SundayStart { get; set; }
        public Nullable<System.DateTime> SundayEnd { get; set; }
        public Nullable<int> SundayBreakMins { get; set; }
        public bool Archived { get; set; }
        public Nullable<int> UserIDCreatedBy { get; set; }
        public Nullable<int> UserIDLastModifiedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> LastModified { get; set; }
    }
}
