//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRTool.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkPattern
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> MondayHours { get; set; }
        public Nullable<decimal> MondayDays { get; set; }
        public Nullable<decimal> MondayStart { get; set; }
        public Nullable<decimal> MondayEnd { get; set; }
        public Nullable<decimal> MondayBreak { get; set; }
        public Nullable<decimal> TuesdayHours { get; set; }
        public Nullable<decimal> TuesdayDays { get; set; }
        public Nullable<decimal> TuesdayStart { get; set; }
        public Nullable<decimal> TuesdayEnd { get; set; }
        public Nullable<decimal> TuesdayBreak { get; set; }
        public Nullable<decimal> ThursdayHours { get; set; }
        public Nullable<decimal> ThursdayDays { get; set; }
        public Nullable<decimal> ThursdayStart { get; set; }
        public Nullable<decimal> ThursdayEnd { get; set; }
        public Nullable<decimal> ThursdayBreak { get; set; }
        public Nullable<decimal> SaturdayHours { get; set; }
        public Nullable<decimal> SaturdayDays { get; set; }
        public Nullable<decimal> SaturdayStart { get; set; }
        public Nullable<decimal> SaturdayEnd { get; set; }
        public Nullable<decimal> SaturdayBreak { get; set; }
        public Nullable<decimal> SundayHours { get; set; }
        public Nullable<decimal> SundayDays { get; set; }
        public Nullable<decimal> SundayStart { get; set; }
        public Nullable<decimal> SundayEnd { get; set; }
        public Nullable<decimal> SundayBreak { get; set; }
        public bool Archived { get; set; }
        public Nullable<int> CSUserIDCreatedBy { get; set; }
        public Nullable<int> CSUserIDLastModifiedBy { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> LastModified { get; set; }
        public Nullable<int> MondayBreakMins { get; set; }
        public Nullable<int> TuesdayBreakMins { get; set; }
        public Nullable<int> WednessdayBreakMins { get; set; }
        public Nullable<int> ThursdayBreakMins { get; set; }
        public Nullable<int> FridayBreakMins { get; set; }
        public Nullable<int> SaturdayBreakMins { get; set; }
        public Nullable<int> SundayBreakMins { get; set; }
        public Nullable<decimal> WednessdayHours { get; set; }
        public Nullable<decimal> WednessdayDays { get; set; }
        public Nullable<decimal> WednessdayStart { get; set; }
        public Nullable<decimal> WednessdayEnd { get; set; }
        public Nullable<decimal> WednessdayBreak { get; set; }
        public Nullable<decimal> FridayHours { get; set; }
        public Nullable<decimal> FridayDays { get; set; }
        public Nullable<decimal> FridayStart { get; set; }
        public Nullable<decimal> FridayEnd { get; set; }
        public Nullable<decimal> FridayBreak { get; set; }
        public bool IsRotating { get; set; }
    }
}
